sudo: required
services:
- docker
before_install:
- docker build -t vetalxpro/docker-react-ci .
script:
- docker run vetalxpro/docker-react-ci npm test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-ci"
  env: "DockerReactCi-env"
  bucket_name: "elasticbeanstalk-us-east-1-970650818193"
  bucket_path: "docker-react-ci"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
