sudo: required
services:
- docker
env:
- DOCKER_COMPOSE_VERSION=1.4.2
- DEV_TAG=vetalxpro/docker-react-ci
before_install:
- docker build -t ${DEV_TAG} -f docker/web/Dockerfile.dev .
script:
- docker run ${DEV_TAG} npm run test -- --coverage
