sudo: required
services:
- docker
env:
- IMAGE_TAG=vetalxpro/docker-react-ci
before_install:
- docker build -t ${IMAGE_TAG} -f docker/web/Dockerfile.ci .
script:
- docker run ${IMAGE_TAG} npm run test -- --coverage
